languague: python
notifications:
  email: false

git:
    submodules: false

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: osx
      sudo: required


install:
  - 'OS=`uname`;
    if [ "$OS" = "Linux" ]; then
      sudo docker pull $DOCKER_IMAGE;
    fi
    '

script:
  - 'OS=`uname`;
    if [ "$OS" = "Linux" ]; then
      echo "Building in Linux";
      sudo docker run --rm -v `pwd`:/workspace $DOCKER_IMAGE /workspace/travis/build-wheels.sh;
    else
      echo "Buildin in Mac";
      sudo ln -s `pwd` /workspace;
      /workspace/travis/build-wheels.sh;
      fi
    '
after_success:
  - pip install twine
  - (twine upload dist/* -u $PYPIUSER -p $PASSWORD --skip-existing  || echo "Not last release")
